apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro3
  labels:
    app: micro3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micro3
  template:
    metadata:
      labels:
        app: micro3
    spec:
      containers:
        - name: micro3
          image: aklilu13/micro3:latest
          ports:
            - containerPort: 8083
          env:
            - name: PORT
              value: "8083"
