apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro2
  labels:
    app: micro2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micro2
  template:
    metadata:
      labels:
        app: micro2
    spec:
      containers:
        - name: micro2
          image: aklilu13/micro2:latest
          ports:
            - containerPort: 8082
          env:
            - name: PORT
              value: "8082"
