namespace: micros-krakend-staging
resources:
  - ../../base
  - krakend-ingress.yaml
images:
  - name: aklilu13/micro1
    newName: aklilu13/micro1
    newTag: latest
  - name: aklilu13/micro2
    newName: aklilu13/micro2
    newTag: latest
  - name: aklilu13/micro3
    newName: aklilu13/micro3
    newTag: latest
  - name: aklilu13/micro4
    newName: aklilu13/micro4
    newTag: latest
configMapGenerator:
  - name: micro1-config
    literals:
      - PORT=8081
  - name: micro2-config
    literals:
      - PORT=8082
  - name: micro3-config
    literals:
      - PORT=8083
  - name: micro4-config
    literals:
      - PORT=8084
